# Generated by Django 3.2.7 on 2021-09-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=255)),
                ('apellido_alumno', models.CharField(max_length=255)),
                ('rut_alumno', models.CharField(max_length=255)),
                ('dv_alumno', models.CharField(max_length=255)),
                ('fecha_nacimiento_alumno', models.DateField()),
                ('apoderado_alumno', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_parentesco', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convivencia.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='CasoVulneracionDerechos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maltrato_fisico', models.CharField(max_length=255)),
                ('maltrato_emocional', models.CharField(max_length=255)),
                ('abuso', models.CharField(max_length=255)),
                ('abandono_negligencia', models.CharField(max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convivencia.alumno')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convivencia.responsablealumno')),
            ],
        ),
    ]
