# Generated by Django 3.2.7 on 2021-09-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convivencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsablealumno',
            name='nombre',
            field=models.CharField(default='Matias', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsablealumno',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='convivencia.alumno'),
        ),
    ]
