# Generated by Django 3.2.7 on 2021-09-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convivencia', '0002_auto_20210912_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsablealumno',
            name='alumno',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apoderado_alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='convivencia.responsablealumno'),
        ),
    ]
