# Generated by Django 3.2.7 on 2021-09-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convivencia', '0003_auto_20210912_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casovulneracionderechos',
            name='responsable',
        ),
        migrations.AddField(
            model_name='casovulneracionderechos',
            name='fecha_caso',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
